#pragma once

static const int
IDC_EDIT_YEAR = 0,
IDC_EDIT_MONTH = 1,
IDC_EDIT_DAY = 2,
IDC_COMBO_AMPM = 3,
IDC_EDIT_HOUR = 4,
IDC_EDIT_MINUTE = 5,
IDC_EDIT_KCAL = 6,
IDC_EDIT_KM = 7,
IDC_EDIT_GRAD = 8,
IDC_EDIT_SPEED = 9,
IDC_BUTTON_SEND = 10
;